### ISSUE TITLE
Uncaught TypeError: You provided an invalid object where a stream was expected. You can provide a...

### ISSUE THREAD

**Issue by DrHardReset** [atom-ide-community/ide-python#223]
Enter steps to reproduce:

1. Open Atom
2. Install package ide-python
3. Error appears

After installation the error appears with each start of atom.

**Atom**: 1.53.0 x64
**Electron**: 6.1.12
**OS**: Windows 8.1
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 1.6.1

### Stack Trace

Uncaught TypeError: You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.

```
At C:\Users\<user>\.atom\packages\ide-python\node_modules\rxjs-compat\bundles\rxjs-compat.umd.min.js:16

TypeError: You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
    at Fa (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:113:292)
    at /packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:27:339)
    at a._innerSub (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:119:416)
    at a._tryNext (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:119:320)
    at a._next (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:119:148)
    at a.next (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:65:253)
    at a.notifyNext (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:120:125)
    at a._next (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:116:50)
    at a.next (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:65:253)
    at /packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:94:79
    at /packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:27:344)
    at a._innerSub (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:119:416)
    at a._tryNext (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:119:320)
    at a._next (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:119:148)
    at a.next (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:65:253)
    at b._subscribe (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:94:79)
    at b._trySubscribe (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:71:376)
    at b.subscribe (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:71:161)
    at b.call (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:118:338)
    at b.subscribe (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:71:34)
    at b.call (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:118:338)
    at b.subscribe (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:71:34)
    at b.call (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:118:338)
    at b.subscribe (/packages/ide-python/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:71:34)
    at listenToRemoteDebugCommands (/packages/ide-python/dist/debugger/utils.js:85:6)
    at activate (/packages/ide-python/dist/debugger/main.js:34:92)
    at PythonLanguageClient.activate (/packages/ide-python/dist/main.js:47:24)
    at Package.activateNow (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:3699687)
    at ~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:14:2607
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:1190051)
```

### Commands

```
     -3:31.5.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-python-run 0.9.7 
ide-python 1.6.1 
```

**Comment by aminya** [comment]
@DrHardReset Could you try the latest version now?

**Comment by annahosanna** [comment]
I no longer receive the error. Thanks

**Comment by aminya** [comment]
You're welcome!

**Comment by DrHardReset** [comment]
Version 1.6.2 does not show the error. Thanks.
