### ISSUE TITLE
Failed to activate the ide-python package

### ISSUE THREAD

**Issue by punkstarman** [atom-ide-community/ide-python#246]
[Enter steps to reproduce:]

1. Upgrade package to version 1.7.1

**Atom**: 1.53.0 x64
**Electron**: 6.1.12
**OS**: Ubuntu 20.04.1
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 1.7.1

### Stack Trace

Failed to activate the ide-python package

```
At /snap/core/current/usr/lib/x86_64-linux-gnu/libstdc  .so.6: version `GLIBCXX_3.4.22' not found (required by /home/wbartlett/.atom/packages/ide-python/node_modules/fuzzaldrin-plus-fast/build/Release/fuzzaldrinplusfast.node)

Error: /snap/core/current/usr/lib/x86_64-linux-gnu/libstdc  .so.6: version `GLIBCXX_3.4.22' not found (required by /home/wbartlett/.atom/packages/ide-python/node_modules/fuzzaldrin-plus-fast/build/Release/fuzzaldrinplusfast.node)
    at process.func (electron/js2c/asar.js:138:31)
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:828:18)
    at Object.func (electron/js2c/asar.js:138:31)
    at Object.func [as .node] (electron/js2c/asar.js:138:31)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/snap/atom/265/usr/share/atom/resources/app/static/<embedded>:11:146814)
    at /packages/ide-python/node_modules/fuzzaldrin-plus-fast/fuzzaldrin-dist.js:1:1650)
    at /packages/ide-python/node_modules/fuzzaldrin-plus-fast/fuzzaldrin-dist.js:1:3551)
    at /packages/ide-python/node_modules/fuzzaldrin-plus-fast/fuzzaldrin-dist.js:4:3)
    at Module.get_Module._compile (/snap/atom/265/usr/share/atom/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/snap/atom/265/usr/share/atom/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/snap/atom/265/usr/share/atom/resources/app/static/<embedded>:11:146814)
    at /packages/ide-python/node_modules/atom-languageclient/build/lib/adapters/autocomplete-adapter.js:14:32)
    at /packages/ide-python/node_modules/atom-languageclient/build/lib/adapters/autocomplete-adapter.js:394:3)
    at Module.get_Module._compile (/snap/atom/265/usr/share/atom/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/snap/atom/265/usr/share/atom/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/snap/atom/265/usr/share/atom/resources/app/static/<embedded>:11:146814)
    at /packages/ide-python/node_modules/atom-languageclient/build/lib/auto-languageclient.js:18:32)
    at /packages/ide-python/node_modules/atom-languageclient/build/lib/auto-languageclient.js:699:3)
    at Module.get_Module._compile (/snap/atom/265/usr/share/atom/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/snap/atom/265/usr/share/atom/resources/app/static/<embedded>:11:151046)
```

### Commands

```
```

### Non-Core Packages

```
atom-ide-base 2.1.1 
atom-ide-datatip 0.20.4 
atom-ide-definitions 0.4.0 
atom-ide-hyperclick 1.0.9 
atom-ide-markdown-service 1.6.0 
atom-ide-outline 1.15.5 
atom-ide-signature-help 0.13.1 
autocomplete-haskell 1.0.1 
busy-signal 2.0.1 
editorconfig 2.6.1 
haskell-ghc-mod 2.2.6 
ide-haskell 2.4.1 
ide-haskell-cabal 2.5.0 
ide-python 1.7.1 
ide-rust 0.22.0-beta.3 
intentions 1.1.5 
language-asciidoc 1.11.0 
language-haskell 1.20.0 
linter 3.1.1 
linter-ui-default 2.2.3 
```

**Comment by aminya** [comment]
Duplicate of https://github.com/atom-community/ide-python/issues/255
